name: CI
on: [push]
defaults:
 run:
  working-directory: ./frontend
jobs:
  eslint:
    name: CleaningWebsite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install packages
        run: npm install
